# Generated by Django 4.2a1 on 2023-02-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('primer_apellido', models.CharField(max_length=50, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(max_length=50, verbose_name='Segundo Apellido')),
                ('fecha', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('ciudad', models.CharField(max_length=50, verbose_name='ciudad')),
                ('estado', models.CharField(max_length=50, verbose_name='estado')),
                ('numero', models.BigIntegerField(null=True, verbose_name='Telefono')),
            ],
        ),
    ]
