# Generated by Django 4.2a1 on 2023-02-08 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='usuario',
        ),
    ]
